// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-C0QCFq0iW2yD7lgGtevc5slGLEbCeRw',
    appId: '1:116284519607:web:ee07e0786c3dac25ac8932',
    messagingSenderId: '116284519607',
    projectId: 'quizzybea',
    authDomain: 'quizzybea.firebaseapp.com',
    storageBucket: 'quizzybea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEX4v-nZ1bEvXmofKf-KCIYTjWznIDr6U',
    appId: '1:116284519607:android:50d6b1de488de14eac8932',
    messagingSenderId: '116284519607',
    projectId: 'quizzybea',
    storageBucket: 'quizzybea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxCQoP_sT1ebkDhDtdwvw_AWMDESNRleA',
    appId: '1:116284519607:ios:7b82edf7ce6e0c01ac8932',
    messagingSenderId: '116284519607',
    projectId: 'quizzybea',
    storageBucket: 'quizzybea.firebasestorage.app',
    iosBundleId: 'com.example.quizzybeaIn',
  );
}
